/**
 * Turns whatever the planner posted into rows that are safe to write.
 *
 * The planner is a static page on another origin, so this payload is entirely
 * client-controlled: every field is re-checked here rather than trusted. Kept
 * apart from the route so it can be exercised without a database.
 */

/** Generous for a personal list, but bounded so one account cannot fill the table. */
export const MAX_TASKS = 500;
export const MAX_SUBTASKS_PER_TASK = 100;
export const MAX_TEXT = 500;

const IMPORTANCE = new Set(["high", "med", "low"]);
const REPEAT_UNITS = new Set(["days", "weeks", "months"]);

const YMD = /^\d{4}-\d{2}-\d{2}$/;
const YMD_HM = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}$/;

export interface NormalisedSubtask {
  id: string;
  text: string;
  completed: boolean;
  dueDate: string | null;
  importance: string | null;
  sortOrder: number;
}

export interface NormalisedTask {
  id: string;
  text: string;
  completed: boolean;
  dueDate: string | null;
  importance: string | null;
  repeatN: number | null;
  repeatUnit: string | null;
  reminder: string | null;
  reminderFired: boolean;
  sortOrder: number;
  subtasks: NormalisedSubtask[];
}

export function cleanText(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  if (!trimmed) return null;
  return trimmed.slice(0, MAX_TEXT);
}

/**
 * Ids are generated by the client (crypto.randomUUID). The character class is
 * deliberately narrow: an id reaches the database as a primary key, and there
 * is no reason for one to contain anything but url-safe characters.
 */
export function cleanId(value: unknown): string | null {
  if (typeof value !== "string") return null;
  const trimmed = value.trim();
  if (!trimmed || trimmed.length > 64) return null;
  return /^[A-Za-z0-9_-]+$/.test(trimmed) ? trimmed : null;
}

/** A calendar day, kept as a string. See the schema comment on PlannerTask. */
export function cleanDate(value: unknown): string | null {
  return typeof value === "string" && YMD.test(value) ? value : null;
}

/** A local wall-clock time, also kept as a string. */
export function cleanReminder(value: unknown): string | null {
  return typeof value === "string" && YMD_HM.test(value) ? value : null;
}

export function cleanImportance(value: unknown): string | null {
  return typeof value === "string" && IMPORTANCE.has(value) ? value : null;
}

export function cleanRepeat(value: unknown): { n: number; unit: string } | null {
  if (!value || typeof value !== "object") return null;
  const raw = value as { n?: unknown; unit?: unknown };
  const n = Number(raw.n);
  if (!Number.isInteger(n) || n < 1 || n > 365) return null;
  if (typeof raw.unit !== "string" || !REPEAT_UNITS.has(raw.unit)) return null;
  return { n, unit: raw.unit };
}

/**
 * The whole posted list, normalised. Rows without a usable id or text are
 * dropped rather than rejected: one malformed entry should not cost a student
 * the rest of their list. Duplicate ids are dropped too, since the reconcile
 * addresses each row once.
 */
export function normaliseTasks(incoming: unknown[]): NormalisedTask[] {
  const tasks: NormalisedTask[] = [];
  const seen = new Set<string>();

  for (let i = 0; i < incoming.length; i++) {
    const raw = incoming[i] as Record<string, unknown>;
    const id = cleanId(raw?.id);
    const text = cleanText(raw?.text);
    if (!id || !text || seen.has(id)) continue;
    seen.add(id);

    const repeat = cleanRepeat(raw?.repeat);
    const subtasksRaw = Array.isArray(raw?.subtasks) ? raw.subtasks : [];
    const subSeen = new Set<string>();
    const subtasks: NormalisedSubtask[] = [];

    for (const s of subtasksRaw.slice(0, MAX_SUBTASKS_PER_TASK)) {
      const sub = s as Record<string, unknown>;
      const sid = cleanId(sub?.id);
      const stext = cleanText(sub?.text);
      if (!sid || !stext || subSeen.has(sid)) continue;
      subSeen.add(sid);
      subtasks.push({
        id: sid,
        text: stext,
        completed: Boolean(sub?.completed),
        dueDate: cleanDate(sub?.dueDate),
        importance: cleanImportance(sub?.importance),
        sortOrder: subtasks.length,
      });
    }

    tasks.push({
      id,
      text,
      completed: Boolean(raw?.completed),
      dueDate: cleanDate(raw?.dueDate),
      importance: cleanImportance(raw?.importance),
      repeatN: repeat?.n ?? null,
      repeatUnit: repeat?.unit ?? null,
      reminder: cleanReminder(raw?.reminder),
      reminderFired: Boolean(raw?.reminderFired),
      // Position in the posted list, not the loop index, so dropped rows do not
      // leave gaps in the ordering.
      sortOrder: tasks.length,
      subtasks,
    });
  }

  return tasks;
}
